### ISSUE TITLE
A request for a documentation resource

### ISSUE THREAD

**Issue by wtllll** [cybergalactic/MSS#11]
Dear Prof.Fossen ：
I ’m a Ph.D. in the direction of unmanned vehicles. I'm very interested in your project. When I was learning the file named clarke83.m. I found you give a reference "Clarke et al. (1983)". But I can't find the arcticle anywhere. Could you please give me more detailed information about it so I can find the arcticle?
                                                                                                                                                                                 Thanks for your time.
                                                                                                                                                                                 Sincerely yours,wtllll.

**Comment by cybergalactic** [comment]
You might find the enclosed article more useful since it compares several methods. I do not have a copy of the original 1983 paper. It might be possible to purchase a copy of the article from the publisher listed in the reference list. Maybe you don’t need this since the equations are in the enclosed paper.

In the following month I will put my lecture notes on https://www.fossen.biz/wiley/index.html. They will cover the same topic.

Cheers

Thor


On 6 Apr 2021, at 05:48, wtllll ***@***.******@***.***>> wrote:



Dear Prof.Fossen ：
I ’m a Ph.D. in the direction of unmanned vehicles. I'm very interested in your project. When I was learning the file named clarke83.m. I found you give a reference "Clarke et al. (1983)". But I can't find the arcticle anywhere. Could you please give me more detailed information about it so I can find the arcticle?
Thanks for your time.
Sincerely yours,wtllll.
