### ISSUE TITLE
about 'otter.m'

### ISSUE THREAD

**Issue by JasonWang2333** [cybergalactic/MSS#43]
Hi there，professor Fossen, I found that the motion equation of otter was  using the function of follows:
![image](https://github.com/cybergalactic/MSS/assets/102033219/958e7cc0-3aa7-4d1a-aef3-a142140e08d6)
so i got 2 questions about it , because i wanna use it to simulate and finish my paper.
The FIRST is, in your book , it says:
![image](https://github.com/cybergalactic/MSS/assets/102033219/31d1cfa8-d56e-4571-b9fa-be7707e91038)
therefore, could i say that, the model you use in the otter.m can only be used in motion of line motion? what if the USV follows a curve? Can i use it to follow the Polyline path？Or i have to use the following equation in your book : 
![image](https://github.com/cybergalactic/MSS/assets/102033219/ae6de9eb-664a-4508-a62d-b00a2d07b01e)
and reconstruct the model?
The SECOND is , i didn't know much about the crossflow drag and strip theory:
![image](https://github.com/cybergalactic/MSS/assets/102033219/b3126d04-d773-450a-a1b1-17a2c68aea39)
but i had looked into some paper and found the strip theory is often used in the calculation of wave disturbance, so i wonder if the crossflow drag the same as wave disturbance? Also, i didn't know where the origin of the equations here:
![image](https://github.com/cybergalactic/MSS/assets/102033219/b0f55c7b-e7d6-47d6-8183-e6ecd277319a)
though i know the Cd_2d coefficient is based on a curve of a paper.
Besides, i have some other questions about the model,  can you reply me the answer even though i know your time is limited and precious?
THIRD, you know the otter model is a 6DOF model, but usually we control the model of 3 degree, so it needs to simplify the model  and transform it into 3 DOF, but i wonder how to decouple the 6DOF model into 3DOF, the only way i could do is to delete the rows and columns of w\p\q ， i wonder if there is better way to do that?
FORTH,  about the hydrodynamic coefficients in this model.
i know all of the hydrodynamic coefficients you use have their experiments and statistics support, however, if i have to consider the variable mass of mp,which may change the draft , as a result , the  hydrodynamic coefficients as well as the draft may be variable all the time, so i wonder if these equations effective while the mass is changing?If it is not  effective, how can i consider the hydrodynamic coefficients of otter?
![image](https://github.com/cybergalactic/MSS/assets/102033219/68ed2053-22ce-4491-8942-231618766e3d)
![image](https://github.com/cybergalactic/MSS/assets/102033219/e70aaf09-c80a-4c98-b6d5-8606e99d3d6d)

Thanks !

**Comment by wtllll** [comment]
您好，已收到您的邮件，谢谢！

**Comment by cybergalactic** [comment]
1) The otter.m model is a 6-DOF model, valid for all motions (not only straight lines). Your question regarding r = 0 is related to ocean currents. The model uses a horizontal ocean current with velocities uc and vc. There are no vertical currents wc. In addition, it is assumed that the time derivative of the ocean current velocity expressed in BODY is zero. This means that the S(omega) v_c term in

<img width="626" alt="Screenshot 2023-10-14 at 10 56 48" src="https://github.com/cybergalactic/MSS/assets/43878665/5fd3cdce-c72f-4e94-b8e4-85a87c7598d1">

is assumed to be zero (only valid if r = 0 or small). You can remove this assumption by adding the S(w) v_c term in the model.  In practice, this term will be minimal. Note the Otter USV model is not affected by this. It is only the current model. However, I will add this term to the GitHub model since you are among many asking this question. 

2) Wave disturbances are not related to the cross-flow drag formula. Strip theory means you slide the hull into pieces and use a 2-D formula for each piece. Then, you sum up along the x-axis (like an integral).  This is the reason you need the 2-D Hoerner formula for drag. The cross-flow drag formula is a nonlinear damping force in sway and yaw using the relative velocity (including the currents' contribution). It is not a wave force. The nonlinear damping terms are in addition to the linear damping terms.

3) You should not simplify your 6-DOF equations of motion. The model should be a high-fidelity 6-DOF model representation of the actual system. Instead, you should make a measurement model, selecting the states you need. You choose the measurements corresponding to surge, sway, and yaw. Then, you compute your control law for the same 3 DOFs. Finally, you define a 6-DOF vector for the control input and substitute your three controls into the vector's surge, sway, and yaw positions. The remaining three elements should be zero. Consequently, there is no need to decouple or reduce the model.

4) You have a new model if you change the load condition (mass, payload, etc.). Then, all mass parameters, CG, CB, and added mass terms change. You can interpolate or extrapolate the data; alternatively, do all computations from scratch for each load condition.

**Comment by JasonWang2333** [comment]
thanks a lot!

**Comment by cybergalactic** [comment]
The otter.m has been updated on GitHub. It now includes the missing S(w) v_c term. The file ExOtter.m explains how to design a course autopilot using the 6-DOF model. No need for model reduction.

**Comment by JasonWang2333** [comment]
I see.
And I will see the updated codes immediately and update my simulation model as well. 
Thanks for your kindness and patience.
