### ISSUE TITLE
Problem in "SIMmariner.m"

### ISSUE THREAD

**Issue by LiangZhao13** [cybergalactic/MSS#65]
Dear Prof. Thor I Fossen, 

I recently find that in the file "SIMmariner.m", Line 58, "psi0" is defined but not being used in the following simulation. I tried to fix it by adding a line after Line 75 as "x(6) = psi0;". It seems the problem is solved with most cases. 

However, I found that the system would fail if we modify the waypoints in Line 48. When the x-coordinate of the second waypoint is a negative value, the system would fail. For example, set the original line 48 as "wpt.pos.x = [0 -2000 5000 3000 6000 10000]';" 

I tried to fix it but find no progress. I would be grateful if you could share some insights to the problem. 

Thank you very much. 

The results would be like this:

![image](https://github.com/user-attachments/assets/5c7cedab-b811-4c60-8d20-1f77035f8fbf)

**Comment by cybergalactic** [comment]
The problem was the proper initialization of the state vectors, starting at yaw/course angles far from 0 degrees. In particular, the default values in the 5-state EKF were not robust for an initial heading of 180 degrees. I have added an optional input to the EKF_5states function, x_prd_init, that solves this. In addition, I have initialized the states in SIMmariner.m to handle all angles in the interval -180 to 180 degrees. You need to download the updated files:

SIMmariner.m
x_hat = EKF_5states.m

The ship will handle 'wpt.pos.x = [0 -2000 5000 3000 6000 10000]' but your prosed path could be better for a large container ship. It would help if you refined the path by adding more waypoints to avoid the sharp turn. The path should always be feasible for this ship. If not, path refinement is the standard procedure.
