### ISSUE TITLE
About CyberShipⅡ

### ISSUE THREAD

**Issue by VastSeaL** [cybergalactic/MSS#66]
Dear Professor Fossen,
    When I use the CyberShipⅡ model in MSS toolbox, I would like to know the inertia matrix of this model and other matirx, such as Coriolis matrix. Where can I find in the toolbox?
    Thank you very much for your time and consideration. I understand you have a busy schedule, and I am grateful for any assistance you can provide.

Looking forward to your response.

**Comment by cybergalactic** [comment]
This is a linearized model for stationkeeping (low speed). Hence, there are no quadratic damping terms due to Coriolis and damping. Adding quadratic Coriolis and centripetal terms might destabilize the model unless you counterbalance this by adding nonlinear damping (ITTC drag, crossflow drag, etc.). It is straightforward to do this using the methods in my textbook. For instance, the Coriolis matrix is computed using the MSS function: C = m2c(M, nu); see Chapter 3. Damping is explained in the chapter covering maneuvering models.

The mass matrix for the model ship is found in initCS2.m. 

The osv.m and SIMosv.m are alternative and more sophisticated models with Corioilis and nonlinear damping.

**Comment by VastSeaL** [comment]
Dear Professor Fossen,
    The CyberShip Ⅱ model ship in simulink, where the inv(M) introduce or input?
![Snipaste_2024-09-02_10-43-35](https://github.com/user-attachments/assets/6f0c50cf-6a28-4b49-9aff-6d1d77b2366a)

**Comment by cybergalactic** [comment]
You will find the model here

…./MSS/VESSELS/models/supply.m

Note that the mass matrix is using bis-scaling.
